version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes: 
      - mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${EXPRESS_MONGO_PORT}:${EXPRESS_MONGO_PORT}
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${EXPRESS_MONGO_HOST}:${MONGO_PORT}/"
  
  web:
    build:
       context: ./
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo_volume:
