name: hello-world
run-name: Hello Nikka
on: [push, workflow_dispatch]

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - name: Set env vars 
        run: echo 'Hello Nikka...!'
        env:
          myNull: ${{ null }}
          myBoolean: ${{ false }}
          myIntegerNumber: ${{ 711 }}
          myFloatNumber: ${{ -9.2 }}
          myHexNumber: ${{ 0xff }}
          myExponentialNumber: ${{ -2.99e-2 }}
          myString: Mona the Octocat
          myStringInBraces: ${{ 'It''s open source!' }}
      - name: Echo env vars
        run: echo ${{ env.myNull }}, ${{ env.myBoolean }}, ${{ env.myIntegerNumber }}, ${{ env.myFloatNumber }}, ${{ env.myHexNumber }}, ${{ env.myExponentialNumber }}, ${{ env.myString }}, ${{ env.myStringInBraces }},
      