name: Splunk Installation

on:
  workflow_dispatch:

jobs:
  download_and_instalation:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Echo
        run: echo "Hello Nikkaa...!"

      - name: Goto /opt
        run: cd /opt

      - name: Download Splunk
        run: wget -O splunk-9.2.0-1fff88043d5f-Linux-x86_64.tgz "https://download.splunk.com/products/splunk/releases/9.2.0/linux/splunk-9.2.0-1fff88043d5f-Linux-x86_64.tgz"

      - name: Extract Tar
        run: tar -xvzf splunk-9.2.0-1fff88043d5f-Linux-x86_64.tgz
    
      - name: Start Splunk
        run: ./splunk/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd "Crest@12345"
      
      - name: Check Splunk Status
        run: ./splunk/bin/splunk status

      - name: Hit The Port 1
        run: curl -I http://localhost:8000
      
      - name: Stop Splunk
        run: ./splunk/bin/splunk stop
        
    #   - name: Hit The Port 2
    #     run: curl -I http://localhost:8000      


